version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=admin_user
      - POSTGRES_DB=mvc